import React from 'react';
import { Subject, ReelCardData, MCQData, FlashcardData, InterviewQuestionData } from './types';

export const REEL_CARDS: ReelCardData[] = [
    { id: 1, subject: Subject.History, title: 'Ancient India', content: 'The Harappan civilization, one of the world\'s oldest urban cultures, flourished in the Indus River basin from about 2500 BCE to 1900 BCE.', gradient: 'from-amber-500 to-orange-600' },
    { id: 2, subject: Subject.Polity, title: 'Fundamental Rights', content: 'Part III of the Indian Constitution (Articles 12-35) contains the Fundamental Rights, which are essential for the all-round development of individuals.', gradient: 'from-sky-500 to-indigo-600' },
    { id: 3, subject: Subject.Geography, title: 'Monsoon Winds', content: 'The Indian monsoon is a seasonal reversal of winds. The southwest monsoon brings heavy rainfall from June to September, crucial for the country\'s agriculture.', gradient: 'from-teal-500 to-cyan-600' },
    { id: 4, subject: Subject.Economy, title: 'NITI Aayog', content: 'The Planning Commission was replaced by NITI Aayog (National Institution for Transforming India) on January 1, 2015, to foster cooperative federalism.', gradient: 'from-rose-500 to-pink-600' },
    { id: 5, subject: Subject.CurrentAffairs, title: 'G20 Summit', content: 'India hosted the G20 summit for the first time in 2023, with the theme "Vasudhaiva Kutumbakam" or "One Earth · One Family · One Future".', gradient: 'from-violet-500 to-fuchsia-600' },
    { id: 6, subject: Subject.Strategy, title: 'Answer Writing', content: 'Consistent practice in answer writing is key. Focus on structure: introduction, body with multiple dimensions, and a forward-looking conclusion.', gradient: 'from-lime-500 to-green-600' },
    { id: 7, subject: Subject.ScienceTech, title: 'Chandrayaan-3', content: 'India\'s Chandrayaan-3 mission successfully soft-landed near the lunar south pole in August 2023, making India the fourth country to achieve a lunar landing.', gradient: 'from-slate-500 to-gray-600' },
    { id: 8, subject: Subject.Environment, title: 'Paris Agreement', content: 'The Paris Agreement is a legally binding international treaty on climate change, adopted by 196 Parties. Its goal is to limit global warming to well below 2 degrees Celsius.', gradient: 'from-emerald-500 to-green-700' },
    { id: 9, subject: Subject.ArtCulture, title: 'Chola Bronzes', content: 'The bronze sculptures of the Chola period are renowned for their exquisite beauty and craftsmanship, with the Nataraja statue being a prime example.', gradient: 'from-yellow-600 to-orange-700' },
    { id: 10, subject: Subject.Polity, title: 'Basic Structure Doctrine', content: 'The Basic Structure Doctrine, established in the Kesavananda Bharati case (1973), holds that Parliament cannot alter the fundamental framework of the Constitution.', gradient: 'from-blue-600 to-indigo-800' },
    { id: 11, subject: Subject.Economy, title: 'UPI Goes Global', content: 'India\'s Unified Payments Interface (UPI) is expanding globally, enabling faster and cheaper cross-border transactions and showcasing India\'s fintech prowess.', gradient: 'from-red-500 to-rose-700' },
    { id: 12, subject: Subject.Ethics, title: 'Ethical Dilemma', content: 'An ethical dilemma involves a conflict between moral imperatives, where obeying one would result in transgressing another. Civil servants often face such situations.', gradient: 'from-purple-500 to-indigo-600' },
];

export const MCQS: MCQData[] = [
    // Polity
    { id: 1, subject: Subject.Polity, question: 'Which article of the Indian Constitution deals with the Right to Equality?', options: ['Article 14', 'Article 19', 'Article 21', 'Article 32'], correctAnswerIndex: 0, explanation: 'Article 14 guarantees equality before the law and equal protection of the laws to all persons within the territory of India.' },
    { id: 2, subject: Subject.Polity, question: 'The concept of "Directive Principles of State Policy" is borrowed from the Constitution of which country?', options: ['USA', 'Ireland', 'UK', 'Canada'], correctAnswerIndex: 1, explanation: 'The DPSP in the Indian Constitution are inspired by the Irish Constitution.' },
    { id: 3, subject: Subject.Polity, question: 'Who administers the oath of office to the President of India?', options: ['The Prime Minister', 'The Speaker of Lok Sabha', 'The Chief Justice of India', 'The Vice President'], correctAnswerIndex: 2, explanation: 'The oath of office to the President is administered by the Chief Justice of India, and in his absence, the senior-most judge of the Supreme Court.' },
    { id: 4, subject: Subject.Polity, question: 'A Money Bill can only be introduced in:', options: ['Lok Sabha', 'Rajya Sabha', 'Either House', 'Joint sitting of both Houses'], correctAnswerIndex: 0, explanation: 'As per Article 110 of the Constitution, a Money Bill can only be introduced in the Lok Sabha with the prior recommendation of the President.' },
    { id: 5, subject: Subject.Polity, question: 'What is the minimum age to be appointed as a Governor of a state in India?', options: ['25 years', '30 years', '35 years', '40 years'], correctAnswerIndex: 2, explanation: 'Article 157 of the Constitution specifies that a person must have completed the age of 35 years to be eligible for appointment as a Governor.' },

    // History
    { id: 6, subject: Subject.History, question: 'The Battle of Plassey was fought in:', options: ['1757', '1764', '1857', '1947'], correctAnswerIndex: 0, explanation: 'The Battle of Plassey was a decisive victory of the British East India Company over the Nawab of Bengal and his French allies on 23 June 1757.' },
    { id: 7, subject: Subject.History, question: 'The "Doctrine of Lapse" was introduced by:', options: ['Lord Cornwallis', 'Lord Wellesley', 'Lord Dalhousie', 'Lord Canning'], correctAnswerIndex: 2, explanation: 'Lord Dalhousie, the Governor-General of India from 1848 to 1856, introduced the Doctrine of Lapse, which was an annexation policy.' },
    { id: 8, subject: Subject.History, question: 'Who among the following was the founder of the "Servants of India Society"?', options: ['Bal Gangadhar Tilak', 'Gopal Krishna Gokhale', 'Mahatma Gandhi', 'Jawaharlal Nehru'], correctAnswerIndex: 1, explanation: 'Gopal Krishna Gokhale, a prominent nationalist leader, founded the Servants of India Society in Pune in 1905.' },
    { id: 9, subject: Subject.History, question: 'The Third Buddhist Council was held at:', options: ['Rajagriha', 'Vaishali', 'Pataliputra', 'Kashmir'], correctAnswerIndex: 2, explanation: 'The Third Buddhist Council was held in 250 BCE at Pataliputra under the patronage of Emperor Ashoka.' },
    { id: 10, subject: Subject.History, question: 'The "Quit India Movement" was launched by Mahatma Gandhi in:', options: ['1920', '1930', '1942', '1947'], correctAnswerIndex: 2, explanation: 'The Quit India Movement was launched at the Bombay session of the All-India Congress Committee by Mahatma Gandhi on 8 August 1942, during World War II.' },

    // Geography
    { id: 11, subject: Subject.Geography, question: 'Which is the highest peak in India?', options: ['Mount Everest', 'K2', 'Kangchenjunga', 'Nanda Devi'], correctAnswerIndex: 2, explanation: 'Kangchenjunga, located in Sikkim, is the highest peak in India and the third highest in the world. K2 is in POK.' },
    { id: 12, subject: Subject.Geography, question: 'The "Saddle Peak" is the highest peak of which Union Territory?', options: ['Lakshadweep', 'Puducherry', 'Andaman & Nicobar Islands', 'Daman & Diu'], correctAnswerIndex: 2, explanation: 'Saddle Peak, located on North Andaman Island, is the highest point of the Andaman and Nicobar archipelago.' },
    { id: 13, subject: Subject.Geography, question: 'Which of the following rivers is also known as the "Sorrow of Bengal"?', options: ['Ganges', 'Brahmaputra', 'Damodar', 'Hooghly'], correctAnswerIndex: 2, explanation: 'The Damodar River was known as the "Sorrow of Bengal" because of its ravaging floods in the plains of West Bengal. However, the construction of several dams has helped to tame it.' },
    { id: 14, subject: Subject.Geography, question: 'Which type of climate is characterized by wet winters and dry summers?', options: ['Equatorial', 'Monsoon', 'Mediterranean', 'Tundra'], correctAnswerIndex: 2, explanation: 'The Mediterranean climate is known for its hot, dry summers and mild, wet winters.' },
    { id: 15, subject: Subject.Geography, question: 'The "Loktak Lake" is located in which state?', options: ['Manipur', 'Mizoram', 'Meghalaya', 'Assam'], correctAnswerIndex: 0, explanation: 'Loktak Lake, the largest freshwater lake in Northeast India, is famous for the phumdis (heterogeneous mass of vegetation, soil, and organic matter) floating over it. It is located in Manipur.' },

    // Economy
    { id: 16, subject: Subject.Economy, question: 'What does "Fiscal Deficit" mean?', options: ['Total revenue minus total expenditure', 'Government\'s total expenditure minus its total revenue, excluding borrowing', 'Revenue deficit plus capital expenditure', 'Government\'s market borrowings'], correctAnswerIndex: 1, explanation: 'Fiscal Deficit is the difference between the total expenditure of the government and its total revenue, which indicates the total borrowing needs of the government.' },
    { id: 17, subject: Subject.Economy, question: 'Which committee recommended the establishment of NABARD?', options: ['Narasimham Committee', 'Sivaraman Committee', 'C. Rangarajan Committee', 'Urjit Patel Committee'], correctAnswerIndex: 1, explanation: 'The B. Sivaraman Committee recommended the establishment of the National Bank for Agriculture and Rural Development (NABARD), which was set up in 1982.' },
    { id: 18, subject: Subject.Economy, question: '"Laffer Curve" explains the relationship between:', options: ['Inflation and Unemployment', 'Tax Rates and Tax Revenue', 'GDP Growth and Income Inequality', 'Poverty and Economic Growth'], correctAnswerIndex: 1, explanation: 'The Laffer Curve suggests that there is an optimal tax rate that maximizes total government tax revenue. Increasing tax rates beyond this point is counter-productive.' },
    { id: 19, subject: Subject.Economy, question: 'What is the "Digital Rupee" or "e-Rupee" recently launched by the RBI?', options: ['A cryptocurrency like Bitcoin', 'A new series of physical banknotes', 'A central bank digital currency (CBDC)', 'A mobile wallet'], correctAnswerIndex: 2, explanation: 'The e-Rupee is a Central Bank Digital Currency (CBDC), which is a digital form of the legal tender issued by the Reserve Bank of India. It is not a cryptocurrency.' },
    { id: 20, subject: Subject.Economy, question: 'Which sector contributes the most to India\'s GDP?', options: ['Agriculture', 'Manufacturing', 'Services', 'Mining'], correctAnswerIndex: 2, explanation: 'The services sector, which includes trade, hotels, transport, communication, and services related to broadcasting, is the largest contributor to India\'s Gross Domestic Product (GDP).' },
    
    // Science & Tech
    { id: 21, subject: Subject.ScienceTech, question: 'What is the primary objective of India\'s Aditya-L1 mission?', options: ['To study the Moon\'s surface', 'To study the Sun\'s corona', 'To explore Mars', 'To study asteroids'], correctAnswerIndex: 1, explanation: 'Aditya-L1 is India\'s first solar observatory mission, designed to study the Sun\'s outermost layers, the corona, and its atmosphere from the Lagrange point 1 (L1).' },
    { id: 22, subject: Subject.ScienceTech, question: 'What is "Li-Fi"?', options: ['A new version of Wi-Fi', 'A wireless communication technology using light', 'A type of lithium battery', 'A programming language'], correctAnswerIndex: 1, explanation: 'Li-Fi (Light Fidelity) is a wireless optical networking technology that uses light-emitting diodes (LEDs) for data transmission.' },
    { id: 23, subject: Subject.ScienceTech, question: 'Which of the following is responsible for the blue color of the sky?', options: ['Reflection', 'Refraction', 'Dispersion', 'Scattering'], correctAnswerIndex: 3, explanation: 'The sky appears blue because of the scattering of sunlight by molecules in the atmosphere, a phenomenon known as Rayleigh scattering. Blue light is scattered more than other colors because it travels as shorter, smaller waves.' },
    { id: 24, subject: Subject.ScienceTech, question: 'The term "Golden Rice" refers to:', options: ['A variety of rice that grows in arid regions', 'A genetically engineered rice with high beta-carotene', 'A rare and expensive variety of Basmati rice', 'Rice cooked with turmeric'], correctAnswerIndex: 1, explanation: 'Golden Rice is a variety of rice produced through genetic engineering to biosynthesize beta-carotene, a precursor of Vitamin A, in the edible parts of rice.' },
    { id: 25, subject: Subject.ScienceTech, question: 'What does "5G" in mobile networks stand for?', options: ['5 Gigahertz', '5th Generation', '5 Gigabytes', '5th Grade'], correctAnswerIndex: 1, explanation: '5G stands for the 5th generation of mobile networks, a significant evolution from the previous 4G LTE networks, offering higher speeds and lower latency.' },

    // Environment
    { id: 26, subject: Subject.Environment, question: 'A "Ramsar Site" is a wetland of international importance under which convention?', options: ['Bonn Convention', 'Ramsar Convention', 'Stockholm Convention', 'Vienna Convention'], correctAnswerIndex: 1, explanation: 'The Ramsar Convention on Wetlands is an international treaty for the conservation and sustainable use of wetlands, also known as the Convention on Wetlands.' },
    { id: 27, subject: Subject.Environment, question: 'The "Chipko Movement" is associated with:', options: ['Water conservation', 'Forest conservation', 'Soil conservation', 'Wildlife protection'], correctAnswerIndex: 1, explanation: 'The Chipko movement was a non-violent social and ecological movement by rural villagers, particularly women, in India in the 1970s, aimed at protecting trees and forests slated for government-backed logging.' },
    { id: 28, subject: Subject.Environment, question: 'What is the main component of Biogas?', options: ['Methane', 'Propane', 'Butane', 'Ethane'], correctAnswerIndex: 0, explanation: 'Biogas is primarily composed of methane (CH4) and carbon dioxide (CO2) and may have small amounts of hydrogen sulfide (H2S), moisture, and siloxanes.' },
    { id: 29, subject: Subject.Environment, question: 'The Kyoto Protocol is an international treaty related to:', options: ['Ozone layer depletion', 'Climate change and greenhouse gas emissions', 'Biodiversity conservation', 'Hazardous waste management'], correctAnswerIndex: 1, explanation: 'The Kyoto Protocol operationalizes the United Nations Framework Convention on Climate Change (UNFCCC) by committing industrialized countries and economies in transition to limit and reduce greenhouse gases (GHG) emissions.' },
    { id: 30, subject: Subject.Environment, question: 'Which National Park is famous for the "one-horned rhinoceros"?', options: ['Jim Corbett National Park', 'Kaziranga National Park', 'Bandipur National Park', 'Kanha National Park'], correctAnswerIndex: 1, explanation: 'Kaziranga National Park in Assam is home to the world\'s largest population of one-horned rhinoceroses.' },
    
    // Art & Culture
    { id: 31, subject: Subject.ArtCulture, question: '"Sattriya" is a classical dance form of which state?', options: ['Odisha', 'Manipur', 'Assam', 'Kerala'], correctAnswerIndex: 2, explanation: 'Sattriya is a major Indian classical dance that originated in the Krishna-centered Vaishnavism monasteries of Assam and is attributed to the 15th-century Bhakti movement scholar and saint Mahapurush Srimanta Sankardev.' },
    { id: 32, subject: Subject.ArtCulture, question: 'The famous "Khajuraho Temples" were built by the rulers of which dynasty?', options: ['Chandela', 'Gupta', 'Maurya', 'Pallava'], correctAnswerIndex: 0, explanation: 'The Khajuraho group of monuments in Madhya Pradesh were built during the rule of the Chandela dynasty between 950 and 1050 AD.' },
    { id: 33, subject: Subject.ArtCulture, question: 'The "Ajanta Caves" are renowned for their:', options: ['Sculptures', 'Mural paintings', 'Rock-cut temples', 'Stupas'], correctAnswerIndex: 1, explanation: 'The Ajanta Caves in Maharashtra are famous for their mural paintings that depict the Jataka tales, which are stories of the previous births of the Buddha.' },
    { id: 34, subject: Subject.ArtCulture, question: 'Which of the following is a prominent festival celebrated in Kerala?', options: ['Bihu', 'Pongal', 'Onam', 'Holi'], correctAnswerIndex: 2, explanation: 'Onam is a major annual harvest festival celebrated by Malayalis in and outside Kerala. It is the official festival of the state and includes a spectrum of cultural events.' },
    { id: 35, subject: Subject.ArtCulture, question: 'The concept of "Shad Darshanas" (Six Schools) is associated with:', options: ['Indian Philosophy', 'Indian Music', 'Indian Dance', 'Indian Architecture'], correctAnswerIndex: 0, explanation: 'Shad Darshanas refers to the six orthodox schools of Hindu philosophy: Samkhya, Yoga, Nyaya, Vaisheshika, Mimamsa, and Vedanta.' },

    // More Miscellaneous MCQs
    { id: 36, subject: Subject.CurrentAffairs, question: 'The term of the Lok Sabha is five years, but it can be extended during a National Emergency for a period of:', options: ['Six months at a time', 'One year at a time', 'Two years at a time', 'Indefinitely'], correctAnswerIndex: 1, explanation: 'During a national emergency, the term of the Lok Sabha can be extended by a law of Parliament for one year at a time for any length of time.' },
    { id: 37, subject: Subject.History, question: 'The "Poona Pact" was signed between Mahatma Gandhi and:', options: ['Lord Irwin', 'Muhammad Ali Jinnah', 'B. R. Ambedkar', 'Subhas Chandra Bose'], correctAnswerIndex: 2, explanation: 'The Poona Pact was an agreement between Mahatma Gandhi and Dr. B. R. Ambedkar on behalf of depressed classes and upper caste Hindu leaders on the reservation of electoral seats for the depressed classes in the legislature of British India in 1932.' },
    { id: 38, subject: Subject.Polity, question: 'The 73rd Constitutional Amendment Act is related to:', options: ['Municipalities', 'Panchayati Raj', 'Official Languages', 'Fundamental Duties'], correctAnswerIndex: 1, explanation: 'The 73rd Amendment Act, 1992, added a new Part IX to the constitution titled "The Panchayats" and granted constitutional status to the Panchayati Raj institutions.' },
    { id: 39, subject: Subject.Economy, question: 'What is "Stagflation"?', options: ['High inflation with high economic growth', 'Low inflation with low economic growth', 'Persistent high inflation combined with high unemployment and stagnant demand', 'A period of deflation'], correctAnswerIndex: 2, explanation: 'Stagflation is a condition of slow economic growth and relatively high unemployment—or economic stagnation—accompanied by rising prices, or inflation.' },
    { id: 40, subject: Subject.Geography, question: 'The "Palk Strait" separates India from which country?', options: ['Maldives', 'Sri Lanka', 'Indonesia', 'Myanmar'], correctAnswerIndex: 1, explanation: 'The Palk Strait is a strait between the Tamil Nadu state of India and the Jaffna District of the Northern Province of the island nation of Sri Lanka.' },
    { id: 41, subject: Subject.Environment, question: 'What is "Eutrophication"?', options: ['The process of water becoming enriched with minerals and nutrients', 'The process of soil erosion', 'The increase of CO2 concentration in the atmosphere', 'The decrease in biodiversity'], correctAnswerIndex: 0, explanation: 'Eutrophication is the process by which a body of water becomes progressively enriched with minerals and nutrients, which can lead to excessive growth of algae (algal blooms) and depletion of oxygen.' },
    { id: 42, subject: Subject.ScienceTech, question: 'ISRO\'s mission "Gaganyaan" is related to:', options: ['Lunar Exploration', 'Mars Orbiter Mission', 'Human Spaceflight Program', 'Solar Study'], correctAnswerIndex: 2, explanation: 'Gaganyaan is an Indian crewed orbital spacecraft intended to be the formative spacecraft of the Indian Human Spaceflight Programme.' },
    { id: 43, subject: Subject.ArtCulture, question: '"Madhubani" painting is a style of folk painting native to which Indian state?', options: ['Rajasthan', 'Bihar', 'West Bengal', 'Uttar Pradesh'], correctAnswerIndex: 1, explanation: 'Madhubani art (or Mithila painting) is a style of Indian painting, practiced in the Mithila region of the Indian subcontinent. This painting is done with a variety of tools, including fingers, twigs, brushes, nib-pens, and matchsticks and using natural dyes and pigments.' },
    { id: 44, subject: Subject.Polity, question: 'The power of the Supreme Court of India to decide disputes between the Centre and the States falls under its:', options: ['Advisory Jurisdiction', 'Appellate Jurisdiction', 'Original Jurisdiction', 'Writ Jurisdiction'], correctAnswerIndex: 2, explanation: 'The original jurisdiction of the Supreme Court extends to disputes between the Government of India and one or more States or between two or more States.' },
    { id: 45, subject: Subject.History, question: 'The capital of the Vijayanagara Empire was:', options: ['Mysore', 'Hampi', 'Belur', 'Badami'], correctAnswerIndex: 1, explanation: 'Hampi, a temple town in northern Karnataka, was the capital of the historic Vijayanagara Empire. The ruins of Hampi are a UNESCO World Heritage Site.' },
    { id: 46, subject: Subject.Economy, question: 'Who is known as the "Father of the Green Revolution" in India?', options: ['Verghese Kurien', 'C. Rangarajan', 'M. S. Swaminathan', 'Norman Borlaug'], correctAnswerIndex: 2, explanation: 'M. S. Swaminathan is renowned as the Father of the Green Revolution in India for his leadership and success in introducing and further developing high-yielding varieties of wheat.' },
    { id: 47, subject: Subject.Geography, question: 'The "Tropic of Cancer" does NOT pass through which of the following Indian states?', options: ['Gujarat', 'Rajasthan', 'Odisha', 'Tripura'], correctAnswerIndex: 2, explanation: 'The Tropic of Cancer passes through 8 Indian states: Gujarat, Rajasthan, Madhya Pradesh, Chhattisgarh, Jharkhand, West Bengal, Tripura, and Mizoram. It does not pass through Odisha.' },
    { id: 48, subject: Subject.Environment, question: 'The Montreal Protocol is related to the:', options: ['Protection of the ozone layer', 'Control of transboundary movement of hazardous wastes', 'Conservation of migratory species', 'Reduction of greenhouse gas emissions'], correctAnswerIndex: 0, explanation: 'The Montreal Protocol is an international treaty designed to protect the ozone layer by phasing out the production of numerous substances that are responsible for ozone depletion.' },
    { id: 49, subject: Subject.Polity, question: 'What does the term "judicial review" mean?', options: ['The power of the judiciary to review its own judgments', 'The power of the judiciary to review the functioning of the executive', 'The power of the judiciary to review and declare the laws passed by the legislature as unconstitutional', 'The power of the President to review judicial decisions'], correctAnswerIndex: 2, explanation: 'Judicial review is a process under which executive or legislative actions are subject to review by the judiciary. A court with judicial review power may invalidate laws and decisions that are incompatible with a higher authority, such as the Constitution.' },
    { id: 50, subject: Subject.History, question: 'The first session of the Indian National Congress was held in:', options: ['Calcutta', 'Bombay', 'Madras', 'Delhi'], correctAnswerIndex: 1, explanation: 'The first session of the Indian National Congress was held from 28–31 December 1885 in Bombay (now Mumbai), and was attended by 72 delegates.' },
];

export const FLASHCARDS: FlashcardData[] = [
    // Polity
    { id: 1, subject: Subject.Polity, question: 'What is a "Writ of Mandamus"?', answer: 'It is a judicial writ issued as a command to an inferior court or ordering a person to perform a public or statutory duty.' },
    { id: 2, subject: Subject.Polity, question: 'What does Article 21 of the Constitution guarantee?', answer: 'Protection of Life and Personal Liberty. No person shall be deprived of his life or personal liberty except according to the procedure established by law.' },
    { id: 3, subject: Subject.Polity, question: 'What is the "Contingency Fund of India"?', answer: 'It is a fund placed at the disposal of the President of India to meet unforeseen expenditures. It is established under Article 267 of the Constitution.' },
    { id: 4, subject: Subject.Polity, question: 'Define "Quorum".', answer: 'Quorum is the minimum number of members of a deliberative assembly necessary to conduct the business of that group. For Lok Sabha and Rajya Sabha, it is one-tenth of the total number of members.' },
    { id: 5, subject: Subject.Polity, question: 'Under which article is the Election Commission of India established?', answer: 'Article 324 of the Constitution provides for the establishment of the Election Commission, vesting in it the power of superintendence, direction, and control of elections.' },
    
    // History
    { id: 6, subject: Subject.History, question: 'Who was the founder of the Mauryan Empire?', answer: 'Chandragupta Maurya, who founded the empire in 322 BCE with the help of Chanakya.' },
    { id: 7, subject: Subject.History, question: 'What was the significance of the "Dandi March"?', answer: 'Also known as the Salt Satyagraha, it was an act of nonviolent civil disobedience led by Mahatma Gandhi in 1930 to protest the British salt tax.' },
    { id: 8, subject: Subject.History, question: 'Who was known as the "Frontier Gandhi"?', answer: 'Khan Abdul Ghaffar Khan, a Pashtun independence activist who was a close associate of Mahatma Gandhi.' },
    { id: 9, subject: Subject.History, question: 'What are the "Four Noble Truths" of Buddhism?', answer: '1. The truth of suffering (Dukkha). 2. The truth of the origin of suffering (Samudāya). 3. The truth of the cessation of suffering (Nirodha). 4. The truth of the path to the cessation of suffering (Magga).' },
    { id: 10, subject: Subject.History, question: 'Who wrote the "Arthashastra"?', answer: 'Chanakya (also known as Kautilya or Vishnugupta), an ancient Indian teacher, philosopher, economist, jurist and royal advisor to Chandragupta Maurya.' },
    
    // Economy
    { id: 11, subject: Subject.Economy, question: 'Define "Repo Rate".', answer: 'The rate at which the Reserve Bank of India (RBI) lends money to commercial banks in the event of any shortfall of funds.' },
    { id: 12, subject: Subject.Economy, question: 'What is "Gross Domestic Product" (GDP)?', answer: 'GDP is the total monetary or market value of all the finished goods and services produced within a country\'s borders in a specific time period.' },
    { id: 13, subject: Subject.Economy, question: 'What is Statutory Liquidity Ratio (SLR)?', answer: 'SLR is the minimum percentage of deposits that a commercial bank has to maintain in the form of liquid cash, gold, or other securities. It is a tool used by the RBI to control credit growth.' },
    { id: 14, subject: Subject.Economy, question: 'Define "Inflation".', answer: 'Inflation is the rate of increase in prices over a given period of time. It is typically a broad measure, such as the overall increase in prices or the increase in the cost of living in a country.' },
    { id: 15, subject: Subject.Economy, question: 'What is "Fiscal Policy"?', answer: 'Fiscal policy is the use of government revenue collection (mainly taxes) and expenditure to influence a country\'s economy.' },
    
    // Geography
    { id: 16, subject: Subject.Geography, question: 'Name the major soil type found in the Deccan Plateau.', answer: 'Black Soil (or Regur soil), which is ideal for cotton cultivation.' },
    { id: 17, subject: Subject.Geography, question: 'What are the "Western Ghats"?', answer: 'A mountain range that runs parallel to the western coast of the Indian peninsula. It is a UNESCO World Heritage Site and one of the eight biodiversity hotspots in the world.' },
    { id: 18, subject: Subject.Geography, question: 'Define "Jet Stream".', answer: 'Jet streams are narrow bands of strong wind that generally blow from west to east at high altitudes in the atmosphere. They have a significant influence on weather patterns.' },
    { id: 19, subject: Subject.Geography, question: 'What is the "El Niño" effect?', answer: 'A climate pattern that describes the unusual warming of surface waters in the eastern tropical Pacific Ocean. It can have significant impacts on weather patterns worldwide, including the Indian monsoon.' },
    { id: 20, subject: Subject.Geography, question: 'Which line of latitude passes through the middle of India?', answer: 'The Tropic of Cancer (23.5° N latitude) passes through the middle of India, dividing it into almost two equal parts.' },

    // Science & Tech
    { id: 21, subject: Subject.ScienceTech, question: 'What is CRISPR-Cas9?', answer: 'It is a revolutionary gene-editing technology that allows scientists to make precise changes to the DNA of organisms. It has vast applications in medicine and agriculture.' },
    { id: 22, subject: Subject.ScienceTech, question: 'What is "Graphene"?', answer: 'An allotrope of carbon consisting of a single layer of atoms arranged in a two-dimensional honeycomb lattice. It is the thinnest, strongest, and most conductive material known.' },
    { id: 23, subject: Subject.ScienceTech, question: 'What is the full form of LASER?', answer: 'Light Amplification by Stimulated Emission of Radiation.' },
    { id: 24, subject: Subject.ScienceTech, question: 'Explain "Blockchain" technology.', answer: 'A decentralized, distributed, and often public, digital ledger consisting of records called blocks that is used to record transactions across many computers so that any involved block cannot be altered retroactively, without the alteration of all subsequent blocks.' },
    { id: 25, subject: Subject.ScienceTech, question: 'What is "Nuclear Fission"?', answer: 'A nuclear reaction in which the nucleus of an atom splits into smaller parts (lighter nuclei), often producing free neutrons and photons (in the form of gamma rays), and releasing a very large amount of energy.' },
    
    // Environment
    { id: 26, subject: Subject.Environment, question: 'Define "Carbon Sequestration".', answer: 'It is the process of capturing and storing atmospheric carbon dioxide. It is one method of reducing the amount of CO2 in the atmosphere with the goal of reducing global climate change.' },
    { id: 27, subject: Subject.Environment, question: 'What is "Biodiversity Hotspot"?', answer: 'A biogeographic region with significant levels of biodiversity that is threatened by human habitation. An area must meet two strict criteria: it must have at least 1,500 vascular plants as endemics, and it has to have lost at least 70% of its primary vegetation.' },
    { id: 28, subject: Subject.Environment, question: 'What is "Acid Rain"?', answer: 'Rain or any other form of precipitation that is unusually acidic, meaning that it has elevated levels of hydrogen ions. It is caused by emissions of sulfur dioxide and nitrogen oxide, which react with the water molecules in the atmosphere.' },
    { id: 29, subject: Subject.Environment, question: 'Define "Food Chain".', answer: 'A linear sequence of organisms where nutrients and energy are transferred from one organism to another. It begins with a producer organism, followed by consumer organisms.' },
    { id: 30, subject: Subject.Environment, question: 'What is the "Greenhouse Effect"?', answer: 'The process by which radiation from a planet\'s atmosphere warms the planet\'s surface to a temperature above what it would be without this atmosphere. Greenhouse gases like CO2, methane, and water vapor trap heat.' },
    
    // Art & Culture
    { id: 31, subject: Subject.ArtCulture, question: 'What are the key features of the Gandhara School of Art?', answer: 'It is a syncretic art style that blended Greek and Roman artistic traditions with Indian subject matter, primarily Buddhist imagery. It flourished in the north-western part of the Indian subcontinent.' },
    { id: 32, subject: Subject.ArtCulture, question: 'What is "Nagara" style of temple architecture?', answer: 'A style of temple architecture that emerged in northern India. It is characterized by a beehive-shaped shikhara (tower), a garbhagriha (sanctum), and a mandapa (pillared hall).' },
    { id: 33, subject: Subject.ArtCulture, question: 'Who are the "Trinity of Carnatic music"?', answer: 'Tyagaraja, Muthuswami Dikshitar, and Syama Sastri, who were three composers of Carnatic music in the 18th century.' },
    { id: 34, subject: Subject.ArtCulture, question: 'What is the significance of the "Elephanta Caves"?', answer: 'Located on Elephanta Island in Mumbai Harbour, these are a network of sculpted caves dedicated to the Hindu god Shiva. They are a UNESCO World Heritage Site.' },
    { id: 35, subject: Subject.ArtCulture, question: 'Which classical dance form is associated with the "Natyashastra"?', answer: 'Bharatanatyam, an Indian classical dance form that originated in Tamil Nadu, is considered to be the oldest classical dance tradition in India and its theory can be traced back to the ancient Sanskrit text "Natyashastra".' },

    // More Miscellaneous Flashcards
    { id: 36, subject: Subject.GeneralKnowledge, question: 'What is the full form of ISRO?', answer: 'Indian Space Research Organisation.' },
    { id: 37, subject: Subject.Polity, question: 'What is a "Zero Hour" in parliamentary proceedings?', answer: 'An informal device available to the members of the Parliament to raise matters without any prior notice. It starts immediately after the question hour and lasts until the agenda for the day is taken up.' },
    { id: 38, subject: Subject.History, question: 'Who gave the slogan "Swaraj is my birthright and I shall have it"?', answer: 'Bal Gangadhar Tilak.' },
    { id: 39, subject: Subject.Economy, question: 'What is "Minimum Support Price" (MSP)?', answer: 'MSP is a form of market intervention by the Government of India to insure agricultural producers against any sharp fall in farm prices. It is announced at the beginning of the sowing season for certain crops.' },
    { id: 40, subject: Subject.Geography, question: 'What is a "Dooar"?', answer: 'The alluvial floodplains in eastern-northeastern India that lie south of the outer foothills of the Himalayas and north of the Brahmaputra River basin. They are known for tea gardens.' },
    { id: 41, subject: Subject.Environment, question: 'What is the "Red Data Book"?', answer: 'A public document created by the International Union for Conservation of Nature (IUCN) for recording rare and endangered species of animals, plants and fungi.' },
    { id: 42, subject: Subject.ScienceTech, question: 'What is the difference between a "Geostationary" and a "Geosynchronous" orbit?', answer: 'A geostationary orbit is a special type of geosynchronous orbit which is circular and lies in the plane of the Earth\'s equator. A satellite in this orbit appears stationary from the ground.' },
    { id: 43, subject: Subject.Polity, question: 'What is the "Basic Structure Doctrine"?', answer: 'A legal principle established by the Supreme Court of India in the Kesavananda Bharati case (1973), which states that the Parliament of India cannot alter certain fundamental features of the Constitution.' },
    { id: 44, subject: Subject.History, question: 'Who was the first Governor-General of independent India?', answer: 'Lord Mountbatten. C. Rajagopalachari was the last Governor-General of India and the only Indian to hold the position.' },
    { id: 45, subject: Subject.Economy, question: 'What is the "Goods and Services Tax" (GST)?', answer: 'An indirect tax used in India on the supply of goods and services. It is a comprehensive, multistage, destination-based tax that has replaced many indirect taxes in India.' },
    { id: 46, subject: Subject.Geography, question: 'What is the "Isthmus of Suez"?', answer: 'The narrow strip of land that lies between the Mediterranean Sea and the Red Sea, linking the continents of Africa and Asia. The Suez Canal was built across it.' },
    { id: 47, subject: Subject.Environment, question: 'Define "Biomagnification".', answer: 'The increasing concentration of a substance, such as a toxic chemical, in the tissues of organisms at successively higher levels in a food chain.' },
    { id: 48, subject: Subject.ArtCulture, question: 'What is the "Dravidian" style of temple architecture?', answer: 'A style of temple architecture that emerged in Southern India. It is characterized by a pyramid-shaped vimana (tower), a garbhagriha (sanctum), and a gopuram (large gateway).' },
    { id: 49, subject: Subject.Polity, question: 'What are the three lists in the Seventh Schedule of the Constitution?', answer: 'The Union List, the State List, and the Concurrent List, which divide legislative powers between the Union and the States.' },
    { id: 50, subject: Subject.History, question: 'What was the "Ryotwari System"?', answer: 'A land revenue system introduced by Thomas Munro in British India. The revenue was paid directly by the ryots (peasant cultivators) to the state.' },
];


export const INTERVIEW_QUESTIONS: InterviewQuestionData[] = [
    { id: 1, category: 'Personal', question: 'Why do you want to join the Civil Services?', answer: 'Focus on the platform it provides for public service, the diversity of challenges, and the opportunity to contribute to nation-building. Link your personal skills and experiences to the demands of the service.' },
    { id: 2, category: 'Situational', question: 'You are a District Magistrate. There is a communal riot in your district. What are your immediate steps?', answer: '1. Impose Section 144. 2. Deploy police forces to sensitive areas. 3. Call for a peace meeting with community leaders. 4. Ensure safety of women and children. 5. Coordinate with higher authorities and manage media communication to prevent rumors.' },
    { id: 3, category: 'Technical', question: 'What are your views on the farm laws that were repealed?', answer: 'Provide a balanced view. Acknowledge the government\'s intent (e.g., market reforms, increasing farmer income) but also discuss the concerns of the farmers (e.g., MSP guarantee, corporate control). Conclude by suggesting a path forward involving wider consultations.' },
    { id: 4, category: 'Personal', question: 'Tell me about your strengths and weaknesses.', answer: 'For strengths, choose qualities relevant to an administrator like integrity, leadership, and problem-solving, and provide brief examples. For weaknesses, choose a real but manageable weakness (e.g., "I sometimes get too involved in details") and explain how you are working to improve it.' },
    { id: 5, category: 'Situational', question: 'How would you use Artificial Intelligence for better governance in your district?', answer: 'I would explore AI for: 1. Predictive analysis for crime prevention. 2. Optimizing traffic management. 3. Efficient delivery of welfare schemes by identifying beneficiaries. 4. Monitoring public infrastructure projects to ensure timely completion. 5. Developing early warning systems for natural disasters.' },
    { id: 6, category: 'Personal', question: 'How do you handle high-pressure situations and stress?', answer: 'Describe a structured approach: 1. I remain calm and focus on prioritizing tasks. 2. I break down complex problems into smaller, manageable parts. 3. I am not hesitant to consult with my team or superiors for guidance. 4. I ensure I maintain a healthy work-life balance through activities like reading or sports to de-stress.' },
    { id: 7, category: 'Technical', question: 'Discuss India\'s "Neighbourhood First" policy and its current challenges.', answer: 'Explain the policy\'s aim to foster friendly relations with neighboring countries. Discuss its successes (e.g., in Bangladesh, Nepal). Then, touch upon challenges like political instability in some nations, cross-border terrorism, and China\'s growing influence in the region, suggesting a need for continuous diplomatic engagement.' },
    { id: 8, category: 'Situational', question: 'Misinformation and fake news are spreading rapidly on social media, causing panic. As a police chief, what actions would you take?', answer: '1. Establish a dedicated social media monitoring cell to identify fake news. 2. Use official social media channels to quickly issue clarifications and fact-checks. 3. Launch a public awareness campaign on how to spot fake news. 4. Take strict legal action against individuals or groups found to be deliberately spreading misinformation.' },
];

// Icons
export const ICONS = {
    reels: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 4v16M17 4v16M3 8h4m10 0h4M3 12h18M3 16h4m10 0h4" /></svg>,
    mcqs: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>,
    flashcards: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2H5a2 2 0 00-2 2v2m14 0h-2" /></svg>,
    interview: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" /></svg>,
};
