import React from 'react';
import { Subject, ReelCardData, MCQData, FlashcardData, InterviewQuestionData, CurrentAffairsData, MindMapData } from './types';

export const REEL_CARDS: ReelCardData[] = [
    { id: 1, subject: Subject.History, title: 'Ancient India', content: 'The Harappan civilization, one of the world\'s oldest urban cultures, flourished in the Indus River basin from about 2500 BCE to 1900 BCE.', gradient: 'from-amber-500 to-orange-600' },
    { id: 2, subject: Subject.Polity, title: 'Fundamental Rights', content: 'Part III of the Indian Constitution (Articles 12-35) contains the Fundamental Rights, which are essential for the all-round development of individuals.', gradient: 'from-sky-500 to-indigo-600' },
    { id: 3, subject: Subject.Geography, title: 'Monsoon Winds', content: 'The Indian monsoon is a seasonal reversal of winds. The southwest monsoon brings heavy rainfall from June to September, crucial for the country\'s agriculture.', gradient: 'from-teal-500 to-cyan-600' },
    { id: 4, subject: Subject.Economy, title: 'NITI Aayog', content: 'The Planning Commission was replaced by NITI Aayog (National Institution for Transforming India) on January 1, 2015, to foster cooperative federalism.', gradient: 'from-rose-500 to-pink-600' },
    { id: 5, subject: Subject.CurrentAffairs, title: 'G20 Summit', content: 'India hosted the G20 summit for the first time in 2023, with the theme "Vasudhaiva Kutumbakam" or "One Earth · One Family · One Future".', gradient: 'from-violet-500 to-fuchsia-600' },
    { id: 6, subject: Subject.Strategy, title: 'Answer Writing', content: 'Consistent practice in answer writing is key. Focus on structure: introduction, body with multiple dimensions, and a forward-looking conclusion.', gradient: 'from-lime-500 to-green-600' },
    { id: 7, subject: Subject.ScienceTech, title: 'Chandrayaan-3', content: 'India\'s Chandrayaan-3 mission successfully soft-landed near the lunar south pole in August 2023, making India the fourth country to achieve a lunar landing.', gradient: 'from-slate-500 to-gray-600' },
    { id: 8, subject: Subject.Environment, title: 'Paris Agreement', content: 'The Paris Agreement is a legally binding international treaty on climate change, adopted by 196 Parties. Its goal is to limit global warming to well below 2 degrees Celsius.', gradient: 'from-emerald-500 to-green-700' },
    { id: 9, subject: Subject.ArtCulture, title: 'Chola Bronzes', content: 'The bronze sculptures of the Chola period are renowned for their exquisite beauty and craftsmanship, with the Nataraja statue being a prime example.', gradient: 'from-yellow-600 to-orange-700' },
    { id: 10, subject: Subject.Polity, title: 'Basic Structure Doctrine', content: 'The Basic Structure Doctrine, established in the Kesavananda Bharati case (1973), holds that Parliament cannot alter the fundamental framework of the Constitution.', gradient: 'from-blue-600 to-indigo-800' },
    { id: 11, subject: Subject.Economy, title: 'UPI Goes Global', content: 'India\'s Unified Payments Interface (UPI) is expanding globally, enabling faster and cheaper cross-border transactions and showcasing India\'s fintech prowess.', gradient: 'from-red-500 to-rose-700' },
    { id: 12, subject: Subject.Ethics, title: 'Ethical Dilemma', content: 'An ethical dilemma involves a conflict between moral imperatives, where obeying one would result in transgressing another. Civil servants often face such situations.', gradient: 'from-purple-500 to-indigo-600' },
    { id: 13, subject: Subject.History, title: 'Ashoka\'s Dhamma', content: 'Ashoka\'s policy of Dhamma was not a new religion but a moral code of conduct based on tolerance, non-violence, and respect for elders, aimed at governing his vast empire peacefully.', gradient: 'from-orange-400 to-red-500' },
    { id: 14, subject: Subject.Geography, title: 'Himalayan River Systems', content: 'The three main Himalayan river systems are the Indus, the Ganga, and the Brahmaputra. These rivers are perennial, fed by both melting snow and rainfall.', gradient: 'from-cyan-400 to-blue-500' },
    { id: 15, subject: Subject.Strategy, title: 'Importance of Mock Tests', content: 'Regularly taking mock tests simulates the exam environment, helps in time management, identifies weak areas, and builds confidence for the actual examination.', gradient: 'from-green-400 to-teal-500' },
];

export const MCQS: MCQData[] = [
    // Polity
    { id: 1, subject: Subject.Polity, question: 'Which article of the Indian Constitution deals with the Right to Equality?', options: ['Article 14', 'Article 19', 'Article 21', 'Article 32'], correctAnswerIndex: 0, explanation: 'Article 14 guarantees equality before the law and equal protection of the laws to all persons within the territory of India.' },
    { id: 2, subject: Subject.Polity, question: 'The concept of "Directive Principles of State Policy" is borrowed from the Constitution of which country?', options: ['USA', 'Ireland', 'UK', 'Canada'], correctAnswerIndex: 1, explanation: 'The DPSP in the Indian Constitution are inspired by the Irish Constitution.' },
    { id: 3, subject: Subject.Polity, question: 'Who administers the oath of office to the President of India?', options: ['The Prime Minister', 'The Speaker of Lok Sabha', 'The Chief Justice of India', 'The Vice President'], correctAnswerIndex: 2, explanation: 'The oath of office to the President is administered by the Chief Justice of India, and in his absence, the senior-most judge of the Supreme Court.' },
    { id: 4, subject: Subject.Polity, question: 'A Money Bill can only be introduced in:', options: ['Lok Sabha', 'Rajya Sabha', 'Either House', 'Joint sitting of both Houses'], correctAnswerIndex: 0, explanation: 'As per Article 110 of the Constitution, a Money Bill can only be introduced in the Lok Sabha with the prior recommendation of the President.' },
    { id: 5, subject: Subject.Polity, question: 'What is the minimum age to be appointed as a Governor of a state in India?', options: ['25 years', '30 years', '35 years', '40 years'], correctAnswerIndex: 2, explanation: 'Article 157 of the Constitution specifies that a person must have completed the age of 35 years to be eligible for appointment as a Governor.' },
    { id: 101, subject: Subject.Polity, question: 'Which Constitutional Amendment Act introduced the Goods and Services Tax (GST)?', options: ['100th Amendment', '101st Amendment', '102nd Amendment', '103rd Amendment'], correctAnswerIndex: 1, explanation: 'The 101st Constitutional Amendment Act, 2016, introduced the Goods and Services Tax (GST) in India, which is a comprehensive indirect tax on manufacture, sale, and consumption of goods and services.' },
    { id: 102, subject: Subject.Polity, question: 'The power of the President of India to issue an ordinance is a:', options: ['Legislative power', 'Executive power', 'Judicial power', 'Constituent power'], correctAnswerIndex: 0, explanation: 'Article 123 of the Constitution grants the President certain law-making powers to promulgate ordinances when either of the two Houses of Parliament is not in session, making it a legislative power.' },
    { id: 103, subject: Subject.Polity, question: 'Who presides over the joint sitting of the two Houses of Parliament?', options: ['The President', 'The Prime Minister', 'The Speaker of the Lok Sabha', 'The Chairman of the Rajya Sabha'], correctAnswerIndex: 2, explanation: 'The Speaker of the Lok Sabha presides over a joint sitting of the two Houses of Parliament. In their absence, the Deputy Speaker of the Lok Sabha presides.' },
    { id: 51, subject: Subject.Polity, question: 'The "Panchayati Raj" system was given constitutional status by which amendment?', options: ['72nd Amendment', '73rd Amendment', '74th Amendment', '42nd Amendment'], correctAnswerIndex: 1, explanation: 'The 73rd Constitutional Amendment Act of 1992 gave constitutional status to the Panchayati Raj institutions, making them a mandatory part of the state structure.' },

    // History
    { id: 6, subject: Subject.History, question: 'The Battle of Plassey was fought in:', options: ['1757', '1764', '1857', '1947'], correctAnswerIndex: 0, explanation: 'The Battle of Plassey was a decisive victory of the British East India Company over the Nawab of Bengal and his French allies on 23 June 1757.' },
    { id: 7, subject: Subject.History, question: 'The "Doctrine of Lapse" was introduced by:', options: ['Lord Cornwallis', 'Lord Wellesley', 'Lord Dalhousie', 'Lord Canning'], correctAnswerIndex: 2, explanation: 'Lord Dalhousie, the Governor-General of India from 1848 to 1856, introduced the Doctrine of Lapse, which was an annexation policy.' },
    { id: 8, subject: Subject.History, question: 'Who among the following was the founder of the "Servants of India Society"?', options: ['Bal Gangadhar Tilak', 'Gopal Krishna Gokhale', 'Mahatma Gandhi', 'Jawaharlal Nehru'], correctAnswerIndex: 1, explanation: 'Gopal Krishna Gokhale, a prominent nationalist leader, founded the Servants of India Society in Pune in 1905.' },
    { id: 9, subject: Subject.History, question: 'The Third Buddhist Council was held at:', options: ['Rajagriha', 'Vaishali', 'Pataliputra', 'Kashmir'], correctAnswerIndex: 2, explanation: 'The Third Buddhist Council was held in 250 BCE at Pataliputra under the patronage of Emperor Ashoka.' },
    { id: 10, subject: Subject.History, question: 'The "Quit India Movement" was launched by Mahatma Gandhi in:', options: ['1920', '1930', '1942', '1947'], correctAnswerIndex: 2, explanation: 'The Quit India Movement was launched at the Bombay session of the All-India Congress Committee by Mahatma Gandhi on 8 August 1942, during World War II.' },
    { id: 104, subject: Subject.History, question: 'The ancient city of "Lothal" was part of which civilization?', options: ['Mesopotamian', 'Indus Valley', 'Egyptian', 'Chinese'], correctAnswerIndex: 1, explanation: 'Lothal was one of the southernmost cities of the ancient Indus Valley Civilization, located in the Bhāl region of the modern state of Gujarāt.' },
    { id: 105, subject: Subject.History, question: 'Who was the Mughal emperor during the 1857 Revolt?', options: ['Akbar II', 'Bahadur Shah Zafar', 'Shah Alam II', 'Aurangzeb'], correctAnswerIndex: 1, explanation: 'Bahadur Shah Zafar was the last Mughal emperor. He was the nominal head of the Indian Rebellion of 1857.' },
    { id: 52, subject: Subject.History, question: 'The "Round Table Conferences" were held in London to discuss:', options: ['India\'s independence', 'Provincial autonomy', 'Future constitutional reforms in India', 'The partition of India'], correctAnswerIndex: 2, explanation: 'The three Round Table Conferences of 1930–32 were a series of peace conferences organized by the British Government to discuss constitutional reforms in India.' },

    // Geography
    { id: 11, subject: Subject.Geography, question: 'Which is the highest peak in India?', options: ['Mount Everest', 'K2', 'Kangchenjunga', 'Nanda Devi'], correctAnswerIndex: 2, explanation: 'Kangchenjunga, located in Sikkim, is the highest peak in India and the third highest in the world. K2 is in POK.' },
    { id: 12, subject: Subject.Geography, question: 'The "Saddle Peak" is the highest peak of which Union Territory?', options: ['Lakshadweep', 'Puducherry', 'Andaman & Nicobar Islands', 'Daman & Diu'], correctAnswerIndex: 2, explanation: 'Saddle Peak, located on North Andaman Island, is the highest point of the Andaman and Nicobar archipelago.' },
    { id: 13, subject: Subject.Geography, question: 'Which of the following rivers is also known as the "Sorrow of Bengal"?', options: ['Ganges', 'Brahmaputra', 'Damodar', 'Hooghly'], correctAnswerIndex: 2, explanation: 'The Damodar River was known as the "Sorrow of Bengal" because of its ravaging floods in the plains of West Bengal. However, the construction of several dams has helped to tame it.' },
    { id: 14, subject: Subject.Geography, question: 'Which type of climate is characterized by wet winters and dry summers?', options: ['Equatorial', 'Monsoon', 'Mediterranean', 'Tundra'], correctAnswerIndex: 2, explanation: 'The Mediterranean climate is known for its hot, dry summers and mild, wet winters.' },
    { id: 15, subject: Subject.Geography, question: 'The "Loktak Lake" is located in which state?', options: ['Manipur', 'Mizoram', 'Meghalaya', 'Assam'], correctAnswerIndex: 0, explanation: 'Loktak Lake, the largest freshwater lake in Northeast India, is famous for the phumdis (heterogeneous mass of vegetation, soil, and organic matter) floating over it. It is located in Manipur.' },
    { id: 106, subject: Subject.Geography, question: 'The "Duncan Passage" is located between:', options: ['South and Little Andaman', 'North and Middle Andaman', 'Little Nicobar and Great Nicobar', 'Andaman and Nicobar'], correctAnswerIndex: 0, explanation: 'The Duncan Passage is a strait in the Indian Ocean. It separates Rutland Island (part of Great Andaman) to the north and Little Andaman to the south.' },
    { id: 53, subject: Subject.Geography, question: 'Which type of soil is most suitable for cotton cultivation?', options: ['Alluvial Soil', 'Red Soil', 'Laterite Soil', 'Black Soil (Regur)'], correctAnswerIndex: 3, explanation: 'Black soils, also known as Regur soils, are rich in clay and are ideal for growing cotton due to their high moisture retention capacity.' },

    // Economy
    { id: 16, subject: Subject.Economy, question: 'What does "Fiscal Deficit" mean?', options: ['Total revenue minus total expenditure', 'Government\'s total expenditure minus its total revenue, excluding borrowing', 'Revenue deficit plus capital expenditure', 'Government\'s market borrowings'], correctAnswerIndex: 1, explanation: 'Fiscal Deficit is the difference between the total expenditure of the government and its total revenue, which indicates the total borrowing needs of the government.' },
    { id: 17, subject: Subject.Economy, question: 'Which committee recommended the establishment of NABARD?', options: ['Narasimham Committee', 'Sivaraman Committee', 'C. Rangarajan Committee', 'Urjit Patel Committee'], correctAnswerIndex: 1, explanation: 'The B. Sivaraman Committee recommended the establishment of the National Bank for Agriculture and Rural Development (NABARD), which was set up in 1982.' },
    { id: 18, subject: Subject.Economy, question: '"Laffer Curve" explains the relationship between:', options: ['Inflation and Unemployment', 'Tax Rates and Tax Revenue', 'GDP Growth and Income Inequality', 'Poverty and Economic Growth'], correctAnswerIndex: 1, explanation: 'The Laffer Curve suggests that there is an optimal tax rate that maximizes total government tax revenue. Increasing tax rates beyond this point is counter-productive.' },
    { id: 19, subject: Subject.Economy, question: 'What is the "Digital Rupee" or "e-Rupee" recently launched by the RBI?', options: ['A cryptocurrency like Bitcoin', 'A new series of physical banknotes', 'A central bank digital currency (CBDC)', 'A mobile wallet'], correctAnswerIndex: 2, explanation: 'The e-Rupee is a Central Bank Digital Currency (CBDC), which is a digital form of the legal tender issued by the Reserve Bank of India. It is not a cryptocurrency.' },
    { id: 20, subject: Subject.Economy, question: 'Which sector contributes the most to India\'s GDP?', options: ['Agriculture', 'Manufacturing', 'Services', 'Mining'], correctAnswerIndex: 2, explanation: 'The services sector, which includes trade, hotels, transport, communication, and services related to broadcasting, is the largest contributor to India\'s Gross Domestic Product (GDP).' },
    { id: 107, subject: Subject.Economy, question: 'What does the term "disinvestment" refer to?', options: ['Closing down public sector units', 'The government selling its assets or a stake in public sector undertakings', 'Investing in foreign companies', 'Allowing private companies to invest in public infrastructure'], correctAnswerIndex: 1, explanation: 'Disinvestment is the action of an organization or government selling or liquidating an asset or subsidiary. In India, it typically refers to the government selling its stake in Public Sector Undertakings (PSUs).' },
    { id: 108, subject: Subject.Economy, question: 'The "Mahalanobis Model" of economic development was adopted in which Five-Year Plan?', options: ['First Five-Year Plan', 'Second Five-Year Plan', 'Third Five-Year Plan', 'Fourth Five-Year Plan'], correctAnswerIndex: 1, explanation: 'The Second Five-Year Plan (1956-61) was based on the Mahalanobis model, which emphasized the development of heavy industries to achieve rapid industrialization.' },
    { id: 54, subject: Subject.Economy, question: 'What is "Minimum Support Price" (MSP)?', options: ['The price at which government sells food grains', 'A price floor set by the government to purchase directly from the farmers', 'The maximum price a farmer can charge', 'The average price of crops in the international market'], correctAnswerIndex: 1, explanation: 'MSP is a form of market intervention by the Government of India to insure agricultural producers against any sharp fall in farm prices. It is announced before the sowing season.' },
    
    // Science & Tech
    { id: 21, subject: Subject.ScienceTech, question: 'What is the primary objective of India\'s Aditya-L1 mission?', options: ['To study the Moon\'s surface', 'To study the Sun\'s corona', 'To explore Mars', 'To study asteroids'], correctAnswerIndex: 1, explanation: 'Aditya-L1 is India\'s first solar observatory mission, designed to study the Sun\'s outermost layers, the corona, and its atmosphere from the Lagrange point 1 (L1).' },
    { id: 22, subject: Subject.ScienceTech, question: 'What is "Li-Fi"?', options: ['A new version of Wi-Fi', 'A wireless communication technology using light', 'A type of lithium battery', 'A programming language'], correctAnswerIndex: 1, explanation: 'Li-Fi (Light Fidelity) is a wireless optical networking technology that uses light-emitting diodes (LEDs) for data transmission.' },
    { id: 23, subject: Subject.ScienceTech, question: 'Which of the following is responsible for the blue color of the sky?', options: ['Reflection', 'Refraction', 'Dispersion', 'Scattering'], correctAnswerIndex: 3, explanation: 'The sky appears blue because of the scattering of sunlight by molecules in the atmosphere, a phenomenon known as Rayleigh scattering. Blue light is scattered more than other colors because it travels as shorter, smaller waves.' },
    { id: 24, subject: Subject.ScienceTech, question: 'The term "Golden Rice" refers to:', options: ['A variety of rice that grows in arid regions', 'A genetically engineered rice with high beta-carotene', 'A rare and expensive variety of Basmati rice', 'Rice cooked with turmeric'], correctAnswerIndex: 1, explanation: 'Golden Rice is a variety of rice produced through genetic engineering to biosynthesize beta-carotene, a precursor of Vitamin A, in the edible parts of rice.' },
    { id: 25, subject: Subject.ScienceTech, question: 'What does "5G" in mobile networks stand for?', options: ['5 Gigahertz', '5th Generation', '5 Gigabytes', '5th Grade'], correctAnswerIndex: 1, explanation: '5G stands for the 5th generation of mobile networks, a significant evolution from the previous 4G LTE networks, offering higher speeds and lower latency.' },
    { id: 109, subject: Subject.ScienceTech, question: 'What is a "Geostationary Orbit"?', options: ['An orbit directly above the Earth\'s equator', 'An orbit that is synchronized with the Earth\'s rotation', 'A polar orbit', 'A low Earth orbit'], correctAnswerIndex: 1, explanation: 'A geostationary orbit is a specific type of geosynchronous orbit directly above the Earth\'s equator (0° latitude), with a period matching the Earth\'s sidereal rotation period. An object in such an orbit appears motionless, at a fixed position in the sky, to ground observers.' },
    { id: 55, subject: Subject.ScienceTech, question: 'What is CRISPR-Cas9?', options: ['A new antibiotic', 'A gene-editing tool', 'A type of cryptocurrency', 'A space telescope'], correctAnswerIndex: 1, explanation: 'CRISPR-Cas9 is a revolutionary technology that allows scientists to edit parts of the genome by removing, adding or altering sections of the DNA sequence.' },

    // Environment
    { id: 26, subject: Subject.Environment, question: 'A "Ramsar Site" is a wetland of international importance under which convention?', options: ['Bonn Convention', 'Ramsar Convention', 'Stockholm Convention', 'Vienna Convention'], correctAnswerIndex: 1, explanation: 'The Ramsar Convention on Wetlands is an international treaty for the conservation and sustainable use of wetlands, also known as the Convention on Wetlands.' },
    { id: 27, subject: Subject.Environment, question: 'The "Chipko Movement" is associated with:', options: ['Water conservation', 'Forest conservation', 'Soil conservation', 'Wildlife protection'], correctAnswerIndex: 1, explanation: 'The Chipko movement was a non-violent social and ecological movement by rural villagers, particularly women, in India in the 1970s, aimed at protecting trees and forests slated for government-backed logging.' },
    { id: 28, subject: Subject.Environment, question: 'What is the main component of Biogas?', options: ['Methane', 'Propane', 'Butane', 'Ethane'], correctAnswerIndex: 0, explanation: 'Biogas is primarily composed of methane (CH4) and carbon dioxide (CO2) and may have small amounts of hydrogen sulfide (H2S), moisture, and siloxanes.' },
    { id: 29, subject: Subject.Environment, question: 'The Kyoto Protocol is an international treaty related to:', options: ['Ozone layer depletion', 'Climate change and greenhouse gas emissions', 'Biodiversity conservation', 'Hazardous waste management'], correctAnswerIndex: 1, explanation: 'The Kyoto Protocol operationalizes the United Nations Framework Convention on Climate Change (UNFCCC) by committing industrialized countries and economies in transition to limit and reduce greenhouse gases (GHG) emissions.' },
    { id: 30, subject: Subject.Environment, question: 'Which National Park is famous for the "one-horned rhinoceros"?', options: ['Jim Corbett National Park', 'Kaziranga National Park', 'Bandipur National Park', 'Kanha National Park'], correctAnswerIndex: 1, explanation: 'Kaziranga National Park in Assam is home to the world\'s largest population of one-horned rhinoceroses.' },
    { id: 110, subject: Subject.Environment, question: 'What is "Biomagnification"?', options: ['Increase in the concentration of a pollutant at a trophic level', 'The process of ecosystem restoration', 'The measurement of biodiversity', 'The creation of biofuels'], correctAnswerIndex: 0, explanation: 'Biomagnification, also known as bioamplification, is the increasing concentration of a substance, such as a toxic chemical, in the tissues of organisms at successively higher levels in a food chain.' },
    { id: 56, subject: Subject.Environment, question: 'What is a "Biodiversity Hotspot"?', options: ['A place with many tourist attractions', 'A region with a high level of endemic species that is under threat', 'A popular national park', 'An area prone to natural disasters'], correctAnswerIndex: 1, explanation: 'A biodiversity hotspot is a biogeographic region with significant levels of biodiversity that is threatened with destruction. An area must meet two strict criteria to be a hotspot.' },

    // Art & Culture
    { id: 31, subject: Subject.ArtCulture, question: '"Sattriya" is a classical dance form of which state?', options: ['Odisha', 'Manipur', 'Assam', 'Kerala'], correctAnswerIndex: 2, explanation: 'Sattriya is a major Indian classical dance that originated in the Krishna-centered Vaishnavism monasteries of Assam and is attributed to the 15th-century Bhakti movement scholar and saint Mahapurush Srimanta Sankardev.' },
    { id: 32, subject: Subject.ArtCulture, question: 'The famous "Khajuraho Temples" were built by the rulers of which dynasty?', options: ['Chandela', 'Gupta', 'Maurya', 'Pallava'], correctAnswerIndex: 0, explanation: 'The Khajuraho group of monuments in Madhya Pradesh were built during the rule of the Chandela dynasty between 950 and 1050 AD.' },
    { id: 33, subject: Subject.ArtCulture, question: 'The "Ajanta Caves" are renowned for their:', options: ['Sculptures', 'Mural paintings', 'Rock-cut temples', 'Stupas'], correctAnswerIndex: 1, explanation: 'The Ajanta Caves in Maharashtra are famous for their mural paintings that depict the Jataka tales, which are stories of the previous births of the Buddha.' },
    { id: 34, subject: Subject.ArtCulture, question: 'Which of the following is a prominent festival celebrated in Kerala?', options: ['Bihu', 'Pongal', 'Onam', 'Holi'], correctAnswerIndex: 2, explanation: 'Onam is a major annual harvest festival celebrated by Malayalis in and outside Kerala. It is the official festival of the state and includes a spectrum of cultural events.' },
    { id: 35, subject: Subject.ArtCulture, question: 'The concept of "Shad Darshanas" (Six Schools) is associated with:', options: ['Indian Philosophy', 'Indian Music', 'Indian Dance', 'Indian Architecture'], correctAnswerIndex: 0, explanation: 'Shad Darshanas refers to the six orthodox schools of Hindu philosophy: Samkhya, Yoga, Nyaya, Vaisheshika, Mimamsa, and Vedanta.' },
    { id: 111, subject: Subject.ArtCulture, question: 'Which Veda is primarily a collection of hymns set to music?', options: ['Rigveda', 'Samaveda', 'Yajurveda', 'Atharvaveda'], correctAnswerIndex: 1, explanation: 'The Samaveda is the Veda of melodies and chants. It is an ancient Vedic Sanskrit text, and part of the scriptures of Hinduism. It is a liturgical text whose 1,875 verses are primary melodies for liturgical recitation.' },
    { id: 57, subject: Subject.ArtCulture, question: 'What are the three main styles of Indian temple architecture?', options: ['Nagara, Dravida, and Vesara', 'Gupta, Maurya, and Chola', 'Buddhist, Jain, and Hindu', 'Rock-cut, Monolithic, and Structural'], correctAnswerIndex: 0, explanation: 'The three main styles of temple architecture are the Nagara style of Northern India, the Dravida style of Southern India, and the Vesara style, which is a hybrid of the two, found primarily in the Deccan region.' },
];

export const FLASHCARDS: FlashcardData[] = [
    // Polity
    { id: 1, subject: Subject.Polity, question: 'What is a "Writ of Mandamus"?', answer: 'It is a judicial writ issued as a command to an inferior court or ordering a person to perform a public or statutory duty.' },
    { id: 2, subject: Subject.Polity, question: 'What does Article 21 of the Constitution guarantee?', answer: 'Protection of Life and Personal Liberty. No person shall be deprived of his life or personal liberty except according to the procedure established by law.' },
    { id: 3, subject: Subject.Polity, question: 'What is the "Contingency Fund of India"?', answer: 'It is a fund placed at the disposal of the President of India to meet unforeseen expenditures. It is established under Article 267 of the Constitution.' },
    { id: 4, subject: Subject.Polity, question: 'Define "Quorum".', answer: 'Quorum is the minimum number of members of a deliberative assembly necessary to conduct the business of that group. For Lok Sabha and Rajya Sabha, it is one-tenth of the total number of members.' },
    { id: 5, subject: Subject.Polity, question: 'Under which article is the Election Commission of India established?', answer: 'Article 324 of the Constitution provides for the establishment of the Election Commission, vesting in it the power of superintendence, direction, and control of elections.' },
    { id: 101, subject: Subject.Polity, question: 'What is a "Prorogation"?', answer: 'Prorogation terminates a session of the House and is done by the President of India. It does not dissolve the House (in the case of Lok Sabha).' },
    { id: 102, subject: Subject.Polity, question: 'Explain the concept of "Separation of Powers".', answer: 'It is a model for the governance of a state where the government is divided into three branches: the legislature, the executive, and the judiciary, each with separate and independent powers and responsibilities so that the powers of one branch are not in conflict with those of the other branches.' },
    { id: 51, subject: Subject.Polity, question: 'What is "Judicial Review"?', answer: 'The power of the judiciary to examine the constitutionality of legislative enactments and executive orders of both the Central and State governments. If they are found to be in violation of the Constitution, they can be declared as illegal, unconstitutional and invalid.' },

    // History
    { id: 6, subject: Subject.History, question: 'Who was the founder of the Mauryan Empire?', answer: 'Chandragupta Maurya, who founded the empire in 322 BCE with the help of Chanakya.' },
    { id: 7, subject: Subject.History, question: 'What was the significance of the "Dandi March"?', answer: 'Also known as the Salt Satyagraha, it was an act of nonviolent civil disobedience led by Mahatma Gandhi in 1930 to protest the British salt tax.' },
    { id: 8, subject: Subject.History, question: 'Who was known as the "Frontier Gandhi"?', answer: 'Khan Abdul Ghaffar Khan, a Pashtun independence activist who was a close associate of Mahatma Gandhi.' },
    { id: 9, subject: Subject.History, question: 'What are the "Four Noble Truths" of Buddhism?', answer: '1. The truth of suffering (Dukkha). 2. The truth of the origin of suffering (Samudāya). 3. The truth of the cessation of suffering (Nirodha). 4. The truth of the path to the cessation of suffering (Magga).' },
    { id: 10, subject: Subject.History, question: 'Who wrote the "Arthashastra"?', answer: 'Chanakya (also known as Kautilya or Vishnugupta), an ancient Indian teacher, philosopher, economist, jurist and royal advisor to Chandragupta Maurya.' },
    { id: 103, subject: Subject.History, question: 'What was the "Ryotwari System"?', answer: 'A land revenue system in British India introduced by Thomas Munro. The revenue was paid directly by the ryots (cultivators) to the State.' },
    { id: 104, subject: Subject.History, question: 'What was the "Ghadar Party"?', answer: 'An Indian revolutionary organisation primarily founded by Punjabi Indians in the United States and Canada with the aim of securing India\'s independence from British rule. Key leaders included Lala Har Dayal and Sohan Singh Bhakna.' },
    { id: 52, subject: Subject.History, question: 'What was the "Doctrine of Lapse"?', answer: 'An annexation policy applied by the British East India Company in India until 1859. If a ruler of a dependent state died without a natural heir, their state would be annexed by the British. It was introduced by Lord Dalhousie.' },

    // Economy
    { id: 11, subject: Subject.Economy, question: 'Define "Repo Rate".', answer: 'The rate at which the Reserve Bank of India (RBI) lends money to commercial banks in the event of any shortfall of funds.' },
    { id: 12, subject: Subject.Economy, question: 'What is "Gross Domestic Product" (GDP)?', answer: 'GDP is the total monetary or market value of all the finished goods and services produced within a country\'s borders in a specific time period.' },
    { id: 13, subject: Subject.Economy, question: 'What is Statutory Liquidity Ratio (SLR)?', answer: 'SLR is the minimum percentage of deposits that a commercial bank has to maintain in the form of liquid cash, gold, or other securities. It is a tool used by the RBI to control credit growth.' },
    { id: 14, subject: Subject.Economy, question: 'Define "Inflation".', answer: 'Inflation is the rate of increase in prices over a given period of time. It is typically a broad measure, such as the overall increase in prices or the increase in the cost of living in a country.' },
    { id: 15, subject: Subject.Economy, question: 'What is "Fiscal Policy"?', answer: 'Fiscal policy is the use of government revenue collection (mainly taxes) and expenditure to influence a country\'s economy.' },
    { id: 105, subject: Subject.Economy, question: 'What is "Priority Sector Lending" (PSL)?', answer: 'A mandate from the RBI to banks to dedicate a certain percentage of their lending to specific sectors of the economy like agriculture, MSMEs, education, housing, etc., which may not get timely and adequate credit otherwise.' },
    { id: 106, subject: Subject.Economy, question: 'Explain "Balance of Payments" (BoP).', answer: 'The Balance of Payments of a country is the record of all economic transactions between the residents of the country and the rest of the world in a particular period of time. It comprises the current account and the capital account.' },
    { id: 53, subject: Subject.Economy, question: 'What is "Stagflation"?', answer: 'A situation in an economy where the inflation rate is high, the economic growth rate slows, and unemployment remains steadily high. It presents a dilemma for economic policy, since actions intended to lower inflation may exacerbate unemployment.' },

    // Geography
    { id: 16, subject: Subject.Geography, question: 'Name the major soil type found in the Deccan Plateau.', answer: 'Black Soil (or Regur soil), which is ideal for cotton cultivation.' },
    { id: 17, subject: Subject.Geography, question: 'What are the "Western Ghats"?', answer: 'A mountain range that runs parallel to the western coast of the Indian peninsula. It is a UNESCO World Heritage Site and one of the eight biodiversity hotspots in the world.' },
    { id: 18, subject: Subject.Geography, question: 'Define "Jet Stream".', answer: 'Jet streams are narrow bands of strong wind that generally blow from west to east at high altitudes in the atmosphere. They have a significant influence on weather patterns.' },
    { id: 19, subject: Subject.Geography, question: 'What is the "El Niño" effect?', answer: 'A climate pattern that describes the unusual warming of surface waters in the eastern tropical Pacific Ocean. It can have significant impacts on weather patterns worldwide, including the Indian monsoon.' },
    { id: 20, subject: Subject.Geography, question: 'Which line of latitude passes through the middle of India?', answer: 'The Tropic of Cancer (23.5° N latitude) passes through the middle of India, dividing it into almost two equal parts.' },
    { id: 107, subject: Subject.Geography, question: 'What is a "Lagoon"?', answer: 'A shallow body of water separated from a larger body of water by barrier islands or reefs. Chilika Lake in Odisha is the largest coastal lagoon in India.' },
    { id: 108, subject: Subject.Geography, question: 'Differentiate between "Weather" and "Climate".', answer: 'Weather refers to short-term atmospheric conditions in a specific place, while climate is the long-term average of weather patterns in a region, typically over 30 years or more.' },
    { id: 54, subject: Subject.Geography, question: 'What is a "Strait"?', answer: 'A narrow passage of water connecting two seas or two other large areas of water. The Palk Strait, for example, connects the Bay of Bengal in the northeast with Palk Bay in the southwest.' },

    // Science & Tech
    { id: 21, subject: Subject.ScienceTech, question: 'What is CRISPR-Cas9?', answer: 'It is a revolutionary gene-editing technology that allows scientists to make precise changes to the DNA of organisms. It has vast applications in medicine and agriculture.' },
    { id: 22, subject: Subject.ScienceTech, question: 'What is "Graphene"?', answer: 'An allotrope of carbon consisting of a single layer of atoms arranged in a two-dimensional honeycomb lattice. It is the thinnest, strongest, and most conductive material known.' },
    { id: 23, subject: Subject.ScienceTech, question: 'What is the full form of LASER?', answer: 'Light Amplification by Stimulated Emission of Radiation.' },
    { id: 24, subject: Subject.ScienceTech, question: 'Explain "Blockchain" technology.', answer: 'A decentralized, distributed, and often public, digital ledger consisting of records called blocks that is used to record transactions across many computers so that any involved block cannot be altered retroactively, without the alteration of all subsequent blocks.' },
    { id: 25, subject: Subject.ScienceTech, question: 'What is "Nuclear Fission"?', answer: 'A nuclear reaction in which the nucleus of an atom splits into smaller parts (lighter nuclei), often producing free neutrons and photons (in the form of gamma rays), and releasing a very large amount of energy.' },
    { id: 109, subject: Subject.ScienceTech, question: 'What is "Artificial Intelligence" (AI)?', answer: 'The simulation of human intelligence in machines that are programmed to think like humans and mimic their actions. The term may also be applied to any machine that exhibits traits associated with a human mind such as learning and problem-solving.' },
    { id: 55, subject: Subject.ScienceTech, question: 'What is ISRO\'s Gaganyaan mission?', answer: 'Gaganyaan is the Indian Human Spaceflight Programme. The objective is to demonstrate the capability to send a crew of three members to an orbit of 400 km for a 3-day mission and bring them back safely to Earth.' },

    // Environment
    { id: 26, subject: Subject.Environment, question: 'Define "Carbon Sequestration".', answer: 'It is the process of capturing and storing atmospheric carbon dioxide. It is one method of reducing the amount of CO2 in the atmosphere with the goal of reducing global climate change.' },
    { id: 27, subject: Subject.Environment, question: 'What is "Biodiversity Hotspot"?', answer: 'A biogeographic region with significant levels of biodiversity that is threatened by human habitation. An area must meet two strict criteria: it must have at least 1,500 vascular plants as endemics, and it has to have lost at least 70% of its primary vegetation.' },
    { id: 28, subject: Subject.Environment, question: 'What is "Acid Rain"?', answer: 'Rain or any other form of precipitation that is unusually acidic, meaning that it has elevated levels of hydrogen ions. It is caused by emissions of sulfur dioxide and nitrogen oxide, which react with the water molecules in the atmosphere.' },
    { id: 29, subject: Subject.Environment, question: 'Define "Food Chain".', answer: 'A linear sequence of organisms where nutrients and energy are transferred from one organism to another. It begins with a producer organism, followed by consumer organisms.' },
    { id: 30, subject: Subject.Environment, question: 'What is the "Greenhouse Effect"?', answer: 'The process by which radiation from a planet\'s atmosphere warms the planet\'s surface to a temperature above what it would be without this atmosphere. Greenhouse gases like CO2, methane, and water vapor trap heat.' },
    { id: 110, subject: Subject.Environment, question: 'What are "Intended Nationally Determined Contributions" (INDCs)?', answer: 'They are the climate action plans submitted by countries under the Paris Agreement. They outline the steps the country intends to take to reduce its greenhouse gas emissions and adapt to the impacts of climate change.' },
    { id: 56, subject: Subject.Environment, question: 'What is "Eutrophication"?', answer: 'The process whereby a body of water becomes overly enriched with minerals and nutrients which induce excessive growth of algae. This process may result in oxygen depletion of the water body.' },

    // Art & Culture
    { id: 31, subject: Subject.ArtCulture, question: 'What are the key features of the Gandhara School of Art?', answer: 'It is a syncretic art style that blended Greek and Roman artistic traditions with Indian subject matter, primarily Buddhist imagery. It flourished in the north-western part of the Indian subcontinent.' },
    { id: 32, subject: Subject.ArtCulture, question: 'What is "Nagara" style of temple architecture?', answer: 'A style of temple architecture that emerged in northern India. It is characterized by a beehive-shaped shikhara (tower), a garbhagriha (sanctum), and a mandapa (pillared hall).' },
    { id: 33, subject: Subject.ArtCulture, question: 'Who are the "Trinity of Carnatic music"?', answer: 'Tyagaraja, Muthuswami Dikshitar, and Syama Sastri, who were three composers of Carnatic music in the 18th century.' },
    { id: 34, subject: Subject.ArtCulture, question: 'What is the significance of the "Elephanta Caves"?', answer: 'Located on Elephanta Island in Mumbai Harbour, these are a network of sculpted caves dedicated to the Hindu god Shiva. They are a UNESCO World Heritage Site.' },
    { id: 35, subject: Subject.ArtCulture, question: 'Which classical dance form is associated with the "Natyashastra"?', answer: 'Bharatanatyam, an Indian classical dance form that originated in Tamil Nadu, is considered to be the oldest classical dance tradition in India and its theory can be traced back to the ancient Sanskrit text "Natyashastra".' },
    { id: 111, subject: Subject.ArtCulture, question: 'What is the "Vesara" style of temple architecture?', answer: 'A hybrid style of temple architecture that combines features of the northern (Nagara) and southern (Dravida) styles. It is predominantly seen in the Deccan region, particularly in Karnataka.' },
    { id: 57, subject: Subject.ArtCulture, question: 'What is "Madhubani" painting?', answer: 'Also known as Mithila painting, it is a style of Indian painting practiced in the Mithila region of Bihar. It is characterized by complex geometrical patterns and is done with fingers, twigs, brushes, and natural dyes.' },
];

export const CURRENT_AFFAIRS_DATA: CurrentAffairsData[] = [
    { id: 1, date: 'October 26, 2023', category: Subject.CurrentAffairs, title: 'National Mission for Clean Ganga (NMCG)', summary: 'The NMCG has been registered as a society, acting as the implementation arm of the National Ganga River Basin Authority (NGRBA). The mission aims to ensure effective abatement of pollution and rejuvenation of the river Ganga by adopting a river basin approach to promote inter-sectoral co-ordination for comprehensive planning and management.' },
    { id: 2, date: 'October 25, 2023', category: Subject.Economy, title: `India's Gig Economy Booms`, summary: `A recent NITI Aayog report estimates that India's gig workforce is expected to expand to 2.35 crore by 2029-30. The report highlights the need for social security measures for gig workers, including income support, health insurance, and skill development opportunities to ensure their well-being and formalization.` },
    { id: 3, date: 'October 24, 2023', category: Subject.ScienceTech, title: 'Advancements in Solid-State Batteries', summary: 'Researchers have developed a new stable electrolyte for solid-state lithium batteries, which could offer higher energy density and improved safety compared to traditional lithium-ion batteries. This breakthrough could revolutionize electric vehicles and portable electronics by providing longer battery life and reducing fire risks.' },
    { id: 4, date: 'October 23, 2023', category: Subject.Polity, title: 'Debate on the Collegium System', summary: 'The system of appointing and transferring judges in India, known as the Collegium System, has once again come under debate. Critics argue for more transparency and accountability, suggesting a National Judicial Appointments Commission (NJAC) as an alternative. Proponents of the collegium system emphasize the importance of judicial independence from the executive.' },
    { id: 5, date: 'October 22, 2023', category: Subject.Environment, title: 'Project Cheetah: One Year Review', summary: 'One year after the reintroduction of cheetahs in Kuno National Park, the project has seen mixed results with several cheetah deaths but also the birth of new cubs. Experts are analyzing the challenges, including habitat adaptation and inter-species competition, to ensure the long-term success of this ambitious conservation project.' },
    { id: 6, date: 'October 21, 2023', category: Subject.CurrentAffairs, title: 'India-Middle East-Europe Economic Corridor (IMEC)', summary: 'Announced at the G20 Summit, the IMEC is a planned infrastructure project to connect India, the Middle East, and Europe through a network of railways and sea lanes. The corridor aims to boost economic development, enhance trade, and foster regional integration, acting as a strategic alternative to China\'s Belt and Road Initiative.' },
    { id: 7, date: 'October 20, 2023', category: Subject.Economy, title: 'Production-Linked Incentive (PLI) Scheme Expansion', summary: 'The Government of India is considering expanding the PLI scheme to more sectors, including toys, furniture, and leather. The scheme aims to boost domestic manufacturing, attract foreign investment, and make India a global manufacturing hub.' },
    { id: 8, date: 'October 19, 2023', category: Subject.Polity, title: 'The Women\'s Reservation Bill 2023', summary: 'The "Nari Shakti Vandan Adhiniyam" was passed by Parliament to reserve one-third of all seats for women in the Lok Sabha and state legislative assemblies. The reservation will be implemented after a delimitation exercise is conducted, following the next census.' },
];

export const INTERVIEW_QUESTIONS: InterviewQuestionData[] = [
    { id: 1, category: 'Personal', question: 'Why do you want to join the Civil Services?', answer: 'Focus on the platform it provides for public service, the diversity of challenges, and the opportunity to contribute to nation-building. Link your personal skills and experiences to the demands of the service.' },
    { id: 2, category: 'Situational', question: 'You are a District Magistrate. There is a communal riot in your district. What are your immediate steps?', answer: '1. Impose Section 144. 2. Deploy police forces to sensitive areas. 3. Call for a peace meeting with community leaders. 4. Ensure safety of women and children. 5. Coordinate with higher authorities and manage media communication to prevent rumors.' },
    { id: 3, category: 'Technical', question: 'What are your views on the farm laws that were repealed?', answer: 'Provide a balanced view. Acknowledge the government\'s intent (e.g., market reforms, increasing farmer income) but also discuss the concerns of the farmers (e.g., MSP guarantee, corporate control). Conclude by suggesting a path forward involving wider consultations.' },
    { id: 4, category: 'Personal', question: 'Tell me about your strengths and weaknesses.', answer: 'For strengths, choose qualities relevant to an administrator like integrity, leadership, and problem-solving, and provide brief examples. For weaknesses, choose a real but manageable weakness (e.g., "I sometimes get too involved in details") and explain how you are working to improve it.' },
    { id: 5, category: 'Situational', question: 'How would you use Artificial Intelligence for better governance in your district?', answer: 'I would explore AI for: 1. Predictive analysis for crime prevention. 2. Optimizing traffic management. 3. Efficient delivery of welfare schemes by identifying beneficiaries. 4. Monitoring public infrastructure projects to ensure timely completion. 5. Developing early warning systems for natural disasters.' },
    { id: 6, category: 'Personal', question: 'How do you handle high-pressure situations and stress?', answer: 'Describe a structured approach: 1. I remain calm and focus on prioritizing tasks. 2. I break down complex problems into smaller, manageable parts. 3. I am not hesitant to consult with my team or superiors for guidance. 4. I ensure I maintain a healthy work-life balance through activities like reading or sports to de-stress.' },
    { id: 7, category: 'Technical', question: 'Discuss India\'s "Neighbourhood First" policy and its current challenges.', answer: 'Explain the policy\'s aim to foster friendly relations with neighboring countries. Discuss its successes (e.g., in Bangladesh, Nepal). Then, touch upon challenges like political instability in some nations, cross-border terrorism, and China\'s growing influence in the region, suggesting a need for continuous diplomatic engagement.' },
    { id: 8, category: 'Situational', question: 'Misinformation and fake news are spreading rapidly on social media, causing panic. As a police chief, what actions would you take?', answer: '1. Establish a dedicated social media monitoring cell to identify fake news. 2. Use official social media channels to quickly issue clarifications and fact-checks. 3. Launch a public awareness campaign on how to spot fake news. 4. Take strict legal action against individuals or groups found to be deliberately spreading misinformation.' },
];

export const MIND_MAP_DATA: MindMapData[] = [
    {
        id: 1,
        subject: Subject.Polity,
        centralTopic: 'Fundamental Rights (Part III)',
        nodes: [
            { topic: 'Article 12: Definition of "State"' },
            { topic: 'Article 13: Laws inconsistent with FRs are void' },
            {
                topic: 'Right to Equality (Art. 14-18)',
                children: [
                    { topic: 'Art. 14: Equality before law & Equal protection of laws' },
                    { topic: 'Art. 15: Prohibition of discrimination' },
                    { topic: 'Art. 16: Equality of opportunity in public employment' },
                    { topic: 'Art. 17: Abolition of Untouchability' },
                    { topic: 'Art. 18: Abolition of titles' },
                ]
            },
            {
                topic: 'Right to Freedom (Art. 19-22)',
                children: [
                    { topic: 'Art. 19: Six Freedoms (Speech, Assembly, etc.)' },
                    { topic: 'Art. 20: Protection in respect of conviction for offences' },
                    { topic: 'Art. 21: Protection of life and personal liberty' },
                    { topic: 'Art. 21A: Right to Education' },
                    { topic: 'Art. 22: Protection against arrest and detention' },
                ]
            },
            {
                topic: 'Right against Exploitation (Art. 23-24)',
                children: [
                    { topic: 'Art. 23: Prohibition of traffic in human beings and forced labour' },
                    { topic: 'Art. 24: Prohibition of employment of children in factories, etc.' },
                ]
            },
            {
                topic: 'Right to Freedom of Religion (Art. 25-28)',
                children: [
                    { topic: 'Art. 25: Freedom of conscience and free profession, practice and propagation of religion' },
                    { topic: 'Art. 26: Freedom to manage religious affairs' },
                ]
            },
            {
                topic: 'Cultural and Educational Rights (Art. 29-30)',
                children: [
                    { topic: 'Art. 29: Protection of interests of minorities' },
                    { topic: 'Art. 30: Right of minorities to establish and administer educational institutions' },
                ]
            },
            {
                topic: 'Right to Constitutional Remedies (Art. 32)',
                children: [
                    { topic: 'Heart and Soul of the Constitution' },
                    { topic: 'Writs: Habeas Corpus, Mandamus, Prohibition, Certiorari, Quo-Warranto' },
                ]
            },
        ]
    }
];


// Icons
export const ICONS = {
    reels: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 4v16M17 4v16M3 8h4m10 0h4M3 12h18M3 16h4m10 0h4" /></svg>,
    mcqs: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>,
    study_tools: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" /></svg>,
    interview: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" /></svg>,
    current_affairs: <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 20H5a2 2 0 01-2-2V6a2 2 0 012-2h10a2 2 0 012 2v1m2 13a2 2 0 01-2-2V7m2 13a2 2 0 002-2V9a2 2 0 00-2-2h-2m-4-3h2m-4 3H9m-4 4h2m-4 4h2m4-8h2m-4 4h2m-4 4h2" /></svg>,
};